spring:
  application:
    name: backend
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SUPABASE_URL}/auth/v1
          jwk-set-uri: ${SUPABASE_URL}/auth/v1/.well-known/jwks.json
          jws-algorithms: ES256
          audiences: authenticated

  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}?connectionTimeZone=Asia/Tokyo&forceConnectionTimeZoneToSession=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

springdoc:
  default-produces-media-type: application/json

mybatis:
  mapper-locations: classpath*:/mapper/*.xml     # XML
  configuration:
    map-underscore-to-camel-case: true